# OS: Linux; Symfony: latest stable; PHP: all the commonly used versions supported by this bundle
name: "Tests - Linux"

on:
  pull_request:
  push:
    branches:
      - 'master'

env:
  fail-fast: true

jobs:
  tests:
    name: "PHP ${{ matrix.php-version }}"
    runs-on: 'ubuntu-latest'
    continue-on-error: false
    strategy:
      matrix:
        php-version: ['8.1','8.2','8.3']
    steps:
      - uses: actions/checkout@v4
        name: Checkout repository

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: ${{ matrix.php-version }}
          tools: composer:v2
          extensions: mbstring, intl, pdo, pdo_sqlite, sqlite3
          ini-values: date.timezone=UTC

      - name: 'Install project dependencies'
        run: |
          composer global config --no-plugins allow-plugins.symfony/flex true
          composer global require --no-progress --no-scripts --no-plugins symfony/flex
          composer update --no-interaction --prefer-dist --optimize-autoloader --prefer-stable
          vendor/bin/simple-phpunit install
      - name: 'Run tests'
        run: vendor/bin/simple-phpunit -v
