# OS: Linux; Symfony: latest stable; PHP: all the commonly used versions supported by this bundle
name: "Tests"

on:
  pull_request:
  push:
    branches:
      - 'main'

env:
  fail-fast: true

jobs:
  tests:
    name: "PHP ${{ matrix.php-version }}"
    runs-on: 'ubuntu-latest'
    continue-on-error: false
    strategy:
      matrix:
        php-version: ['8.1', '8.2', '8.3', '8.4']
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v5

      - name: 'Install PHP with extensions'
        uses: shivammathur/setup-php@v2
        with:
          coverage: xdebug
          php-version: ${{ matrix.php-version }}
          tools: composer:v2
          extensions: mbstring, intl
          ini-values: date.timezone=UTC

      - name: 'Install project dependencies'
        run: |
          composer global config --no-plugins allow-plugins.symfony/flex true
          composer global require --no-progress --no-scripts --no-plugins symfony/flex
          composer update --no-interaction --prefer-dist --optimize-autoloader --prefer-stable
          vendor/bin/simple-phpunit install
      - name: 'Run tests'
        run: XDEBUG_MODE=coverage vendor/bin/phpunit --coverage-clover ./coverage.xml

      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1.3.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          # or
          # api-token: ${{ secrets.CODACY_API_TOKEN }}
          coverage-reports: <PATH_TO_REPORT>
          # coverage-reports: <PATH_TO_REPORT>, <PATH_TO_REPORT>       